### ISSUE TITLE
Compiling on AIX or cross multi platform support

### ISSUE THREAD

**Issue by hansaya** [mdolidon/endlines#10] opened 2016-05-06 15:38 UTC
When I try to compile on a AIX box I get 
`"walkers.c", line 210.25: 1506-022 (S) "d_type" is not a member of "struct dirent".
`

I manage to fix this by following http://stackoverflow.com/questions/2197918/cross-platform-way-of-testing-whether-a-file-is-a-directory

I think this will help others, when trying to compile on multiple platforms.

BTW done a good job on the project and I love it

**Comment by mdolidon** [comment] 2016-05-07 18:35
Hello Hans. Is this with the current master branch (resp. tag 1.6.2 ?).
This kind of issues arose as the initial code was BSD oriented (the project being born on Apple OSX), but I fixed that in 1.6.2 actually to make it more digestible by other POSIX platforms. And as I check, there's no mention of `d_type` in `walkers.c` anymore in that version. :) Could you please confirm ?

**Comment by hansaya** [comment] 2016-05-09 16:17
Yes I had an older version. sorry about that. New code doesn't contain any d_types anymore. I'm working on getting the new code compiled on a AIX and seems like I need to get m4 before I can proceed. I'll post when I get it working

**Comment by mdolidon** [comment] 2016-05-10 07:13
I'll be very interested in the outcome. I had taken the chance of using M4 as it seemed pretty ubiquitous in standard distributions (most any Linux, OSX, *BSD, even MinGW comes with an M4 by default). Checking IBM's doc ( http://www.ibm.com/support/knowledgecenter/ssw_aix_72/com.ibm.aix.cmds3/m4.htm ) I see that the M4 they ship does not seem to recognize option -P which I use to separate M4 from C more clearly.
If compiling is a hassle on AIX, I may need to find a workaround, either not using M4 anymore or including the macro output in the source. Please keep me posted ! :)

**Comment by hansaya** [comment] 2016-05-10 19:31
I managed to install m4 but seems like different version and it didnt contain any -P argument but work without it. But then I kept running into this 

`xlc src/walkers.c src/engine.c src/main.c`
`src/walkers.c:`
`src/engine.c:`
`"src/engine.c", line 1: 1506-229 (W) File is empty.`
`"src/engine.c", line 1.1: 1506-356 (W) Compilation unit is empty.`
`src/main.c:`
`ld: 0711-317 ERROR: Undefined symbol: .engine_run`
`ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.`
`make: 1254-004 The error code from the last command is 8.``

This is the help output of m4 on AIX
`
Usage: m4 [-els] [-B Number] [-D Name[=Value]]... [-H Number]
       [-I Directory] [-S Number] [-T Number] [-U Name]... [File...]
`

Package is under http://www-03.ibm.com/systems/power/software/aix/linux/toolbox/alpha.html

**Comment by hansaya** [comment] 2016-05-10 19:49
However If run m4 on linux machine and copy engine.c over to the AIX box it works and I dont see any issues with it. I didnt look at the code to see what the macro does exactly but might not effect much.

**Comment by mdolidon** [comment] 2016-05-11 07:33
The Linux generated .c file is indeed exactly the same as what you'd want on AIX. The compilation errors you get on AIX are apparently caused by IBM's M4 outputting an empty .c file, because of it not recognizing the -P option. I'll push a fix for this next week (on the road this week, no unix dev station around). With my big thanks for giving me feedback on this exotic environment ! :+1:

**Comment by hansaya** [comment] 2016-05-11 16:00
Other thing I would add to this scenario is the csum support to runtest.sh. csum is the AIX way of doing md5. I think it works the same way as md5sum http://www-01.ibm.com/support/docview.wss?uid=swg21496703

**Comment by mdolidon** [comment] 2016-05-16 19:51
Back home. As promised, did the tiny update. Hans, could you please try this : 

```
git clone https://github.com/mdolidon/endlines
cd endlines
git pull origin aix
git checkout aix
make test
```

...and let me know whether that worked on your AIX system ?

**Comment by hansaya** [comment] 2016-05-17 20:49
That didnt work, something to do with how the script runs. 
I get 

```
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : oldmac output doesn't match
FAILURE : windows output doesn't match
OK : unix output
OK : preserves file permissions
csum: 1493-001 Unable to access one or more specified files.
FAILURE : using with pipes yielded non matching output
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
OK : empty file passes
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : UTF-8
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : UTF-16 Little Endian
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : UTF-16 Big Endian
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : large file processing ; buffered access mechanism may be damaged
FAILURE : failed to react to an unknown convention
FAILURE : keeps chatting even though -q was used
FAILURE : didn't mention skipping a binary file
OK : option -b forces conversion of binaries
FAILURE : didn't mention skipping a binary file with a known extension
OK : option -b forces conversion of binaries with known extension
FAILURE : a file time was changed when it shouldn't, or kept when it shouldn't
./runtest.sh: line 293: ../endlines: A file or directory in the path name does not exist.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
csum: 1493-001 Unable to access one or more specified files.
FAILURE : failure to handle multiple files
FAILURE : didn't mention hitting a non-existent file name
FAILURE : didn't mention hitting a an unreadable file
FAILURE : didn't mention hitting a write protected file
FAILURE : didn't mention unability to create temporary file

```

I might have to dbug this further more and I'll let you know how it goes

**Comment by mdolidon** [comment] 2016-05-17 21:24
That'd be nice. It's pretty akward to write for a system I don't have access to. Feel free to play around and fork / request a pull if you get it right ! :)

In the meanwhile, I assume that at least it compiled neatly on AIX this time.

**Comment by hansaya** [comment] 2016-05-17 21:52
so problem with test.sh file is when you call csum<file, you get

```
csum<unixref
0f2cf8192da27ebd20b5d8721f358aaa  -
csum: 1493-001 Unable to access one or more specified files.
```

So maybe there is a better way of removing tail end of the return of csum. This weekend I'll take a crack at it to fix the test file and the makefile since I have other problems with using make with that make file. AIX comes with full of surprises :)

To you question about m4, it works now when I ran it manualy. And i compiled it manually after that

**Comment by mdolidon** [comment] 2016-05-18 08:41
OK. Yes I think that all checksum utilities can be fed by simply specifying the file name in the parameters, besides (for md5 and md5sum) piping the contents into stdin. So it'd just be about removing all the < syntaxes. I'll do that.

**Comment by hansaya** [comment] 2016-05-18 15:00
I got everything running with a minor warning from the compiler
I changed the make file from

```
endlines: $(OBJECTS)
    $(CC) $(LDFLAGS) $(OBJECTS) -o $@

.o:
    $(CC) -c $(CFLAGS) -o $@
```

to

```
endlines: $(OBJECTS)
    $(CC) $(LDFLAGS) -o $@ $(OBJECTS)

.c.o:
    $(CC) $(CFLAGS) -c $<  -o $@
```

Why the make file change? im not a expert on makefiles but make was creating object files out of src folder and that cause issue when binding. Above change fixed that and this should work on other  platforms. you may ask what warning you talking about? I was using xlc as the compiler and it did not support -Wall flag. So I was getting

```
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-289 (W) Option -Wall was incorrectly specified. The option will be ignored.
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument

```

This is very minor and I dont think you need to look into it. Since compiler just ignores it

For the test, I did
Veriable=`$MD5 filename | awk '{ print $1 }'`
This fixed all the test problems and everything ran fine after that

**Comment by mdolidon** [comment] 2016-05-19 21:36
I've updated the makefile and runtest.sh as per your findings. However I attempt `csum - < file` rather than piping throug awk, in hope of keeping that part independent of the hashing program that'll be used (md5 and md5sum have different outputs).

That new version is still in the `aix` branch. Hopefully it compiles and tests flawlessly this time. :) Apart of the warning for the -Wall option, indeed, I'll live with that one. I'm not willing to drop that option from the standard compilation process, and attempting to detect the compiler beforehand would most likely shift the problem around and make it bigger. :D

**Comment by hansaya** [comment] 2016-05-23 13:57
Perfect, everything working +1: 

Here is the output:

```
$ export CC=xlc
$ make endlines
        xlc -O3 -Wall -std=c99 -c src/walkers.c -o src/walkers.o
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-289 (W) Option -Wall was incorrectly specified. The option will be ignored.
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument
        m4 src/engine.c.m4 > src/engine.c
        xlc -O3 -Wall -std=c99 -c src/engine.c -o src/engine.o
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-289 (W) Option -Wall was incorrectly specified. The option will be ignored.
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument
        xlc -O3 -Wall -std=c99 -c src/main.c -o src/main.o
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-289 (W) Option -Wall was incorrectly specified. The option will be ignored.
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument
        xlc  -o endlines src/walkers.o src/engine.o src/main.o
$ chmod 755 test/runtest.sh
$ make test
        (cd test; ./runtest.sh)

OK : oldmac output
OK : windows output
OK : unix output
OK : preserves file permissions
OK : using with pipes
OK : empty file passes
OK : UTF-8
OK : UTF-16 Little Endian
OK : UTF-16 Big Endian
OK : large file processing
OK : reacts to an unknown convention
OK : quietens down with -q
OK : skips binaries
OK : option -b forces conversion of binaries
OK : skips binaries with known extension without reading contents
OK : option -b forces conversion of binaries with known extension
OK : option -k preserves the file's modification time
OK : multiple files
OK : notifies the user if a file can't be opened
OK : notifies the user if a file can't be read
OK : notifies the user if a file is write protected
OK : notifies the user if the temporary file can not be created

All tests succeeded

```

Sorry for taking so long to reply. I think we can close this ticket now :)

**Comment by mdolidon** [comment] 2016-05-23 14:26
That's great. Thanks to you we've made a nice step towards buffing out the burrs that were chafing when moving across unix boundaries. Your ticket has let to a very helpful process !
Take care.

**Closed as completed** 2016-05-23 14:30 UTC
Labels: enhancement
